name: Deploy to gh-pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: "Deploy to Github Pages"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - run: cd client
      # Yarn equivalent of npm ci.
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: build
          keep_history: true
          verbose: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
